### ISSUE TITLE
firewall_multi for imcp types

### ISSUE THREAD

**Issue by mmckinst** [alexharv074/puppet-firewall_multi#1]
would be a nice feature. related bug report (not mine) https://tickets.puppetlabs.com/browse/MODULES-1141

**Comment by alexharv074** [comment]
Sure, I'll look into it.

**Comment by alexharv074** [comment]
Yes, it can be done, and you forced me to improve the design a little; thanks.  Before I do this, are there any other array inputs you know of that we should support aside from these?

**Comment by alexharv074** [comment]
Version 1.1.1 released that introduces this feature.

**Comment by mmckinst** [comment]
Thanks! ICMP was the only other array input I needed. Hopefully puppetlabs-firewall will support arrays at some point in the future, its so disappointing its lacking that feature.

**Comment by alexharv074** [comment]
I wouldn't hold your breath.  I looked into trying to add these features myself to the provider, and it would be very difficult to do.  The real issue is that the underlying provider - i.e. iptables - doesn't support arrays either, whereas a firewall resource is a representation of a single iptables entry.  That's why I wrote this module.

**Comment by alexharv074** [comment]
@mmckinst Fyi I've rewritten this putting most of the work in a custom function; much cleaner.  If you upgrade your catalogs won't be polluted with all the intermediary defined types any more.  It should also be easy to extend going forward.

**Comment by mmckinst** [comment]
nice. so much cleaner now. can you tag the releases in github too?

**Comment by alexharv074** [comment]
Ok, releases are all tagged.
