### ISSUE TITLE
guessing provider using Stdlib::IP::Address::V6

### ISSUE THREAD

**Issue by maxadamo** [alexharv074/puppet-firewall_multi#21]
hello @alexharv074 ,

I try to explain the reason for this request. 
Actually, we have arrays of IPs in hiera. For instance we have one called `trusted_network`, which lists a bunch of IPv6 and IPv4 networks. 

In order to use it, until now I am doing the following: 
```
$trusted_networks.each | String $source | {
  if $source =~ Stdlib::IP::Address::V6 { $provider = 'ip6tables' } else { $provider = 'iptables' }
  firewall { "310 allow inbound to HTTP, HTTPS for ${provider} from ${source}":
    action   => accept,
    provider => $provider,
    chain    => 'INPUT',
    source   => $source,
    dport    => [80,443],
    proto    => tcp;
  }
}
```
what I was thinking is to omit the `provider` and use directly the array. But in this case `firewall_multi` needs to guess the provider (perhaps you can use the above `Stdlib::IP::Address::V6`): 
```
firewall_multi { '310 allow inbound to HTTP, HTTPS':
  action => accept,
  chain  => 'INPUT',
  source => $trusted_networks,
  dport  => [80,443],
  proto  => tcp;
}
```

**Comment by alexharv074** [comment]
Hi @maxadamo , I am not opposed in principle to any improvement to this module that is backwards compatible and will not cause upgrade issues for others.

In this case, however, I feel that if the firewall module does not offer to "guess" the provider in the way you suggest, it would be surprising to me if this module did that. Perhaps it is better to discuss with the Modules team at Puppet to see if they would like to implement your suggestion in the firewall module instead?

Another idea is why not refactor your $trusted_network so that it looks more like this?:

```
$trusted_network = {
  'ipv4' => ['1.1.1.1','2.2.2.2'],
  'ipv6' => ['::ffff:1.1.1.1','::ffff:2.2.2.2']
}
```

Won't that be a cleaner as well?

**Comment by maxadamo** [comment]
will be resolved by https://tickets.puppetlabs.com/browse/MODULES-9848

**Comment by alexharv074** [comment]
Thanks for the update @maxadamo
