### ISSUE TITLE
Plans to support Red Hat 8.x/9.x and derivatives? 

### ISSUE THREAD

**Issue by mick-t** [alexharv074/puppet-firewall_multi#39]
Hi,

I'm looking to use `[puppet-firewall_multi](https://github.com/alexharv074/puppet-firewall_multi)` and the [Puppet Forge](https://forge.puppet.com/modules/alexharvey/firewall_multi/readme) page says that Red Hat 5,6,7 are supported. Are there any plans to support 8.x and 9.x?

Thanks
--Mick

**Comment by alexharv074** [comment]
Hi @mick-t  I have not actually tested this for real on various platforms in a long time, because actually it should work on all linux. Could you try it out for me, and if it works I'll update the advertised lists of platforms.

**Comment by alexharv074** [comment]
@robertc99  which platforms are you using? Is it safe for me to just update this to say RHEL 8 & 9 are supported? I'm ~ 99% sure that there is nothing that can go wrong in this module with respect to the underlying platform that would not have to firstly go wrong and be fixed in the firewall module itself.

**Comment by robertc99** [comment]
yes we are using rhel8/9 derivates. so rocky and alma Linux.

**Comment by alexharv074** [comment]
@mick-t  I have released a bugfix release 7.0.3 which correctly advertises all supported platforms.
